### ISSUE TITLE
Fix fonts (Inter) on Windows (and maybe Linux) machines

### ISSUE THREAD

**Issue by skull8888888** [lmnr-ai/lmnr#130] opened 2024-11-01 18:49 UTC
For some reason Inter font is not loading on Windows machines.

This is how font should look like. On windows it defaults to ubuntu mono for some reason.

<img width="1071" alt="Screenshot 2024-11-01 at 11 48 37 AM" src="https://github.com/user-attachments/assets/d95d2aca-58f1-4f61-9d9a-6acfeec19ad1">

**Comment by lucky29-git** [comment] 2024-11-03 18:33
Hey @skull8888888 
can you please assign this to me? 
I will give you an update regarding this soon.

**Comment by lucky29-git** [comment] 2024-11-19 04:08
Hey @skull8888888 
Sorry I'm in the middle of my exams and placement session, was a bit busy.
I checked the font in both windows and ubuntu, it seems fine to me 

in ubuntu
![image](https://github.com/user-attachments/assets/ebb13941-39bc-4322-8c54-7d06461f0e10)

in windows
![Screenshot (834)](https://github.com/user-attachments/assets/fde6ded7-af11-4b33-9f8d-c8cacec916b7)

can you please check if the issue is still there?

**Comment by skull8888888** [comment] 2024-11-19 04:11
yep, as you can see from your screenshots and mine screenshot in the issue description, the fonts are clearly different. Yours looks like ubuntu mono, correct one should be inter.

**Comment by lucky29-git** [comment] 2024-11-19 04:17
Okayy @skull8888888, working on it rn.

**Comment by dinmukhamedm** [comment] 2024-12-01 01:30
@lucky29-git I unassigned this from you as per Discord discussion. Could you please briefly describe here what you have already tried and it not worked?

**Comment by dinmukhamedm** [comment] 2024-12-06 01:26
Thanks for the attempt. Now fixed via #260

**Closed by dinmukhamedm** 2024-12-06 01:26 UTC
Labels: bug, good first issue, help wanted, frontend, UI
